// Helper to generate a date string N days ago from a reference date
const daysAgo = (refDate, n) => {
  const d = new Date(refDate);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

const REF = "2026-02-18T00:00:00Z";

export const ORDERS_MOCK = [
  // --- Today (Day 0) ---
  {
    id: "ORD-001",
    customerName: "Budi Santoso",
    phone: "081234567890",
    type: "Makan di Sini",
    table: "A1",
    items: [
      { name: "Waffle with Berries", quantity: 2, price: 35000 },
      { name: "Vanilla Bean Crème Brûlée", quantity: 1, price: 40000 },
    ],
    totalPrice: 110000,
    status: "Preparing",
    timestamp: daysAgo(REF, 0),
    isTakeaway: false,
  },
  {
    id: "ORD-002",
    customerName: "Siti Aminah",
    phone: "081987654321",
    type: "Bawa Pulang",
    people: 4,
    items: [{ name: "Macaron Mix of Five", quantity: 3, price: 45000 }],
    totalPrice: 135000,
    status: "Paid",
    timestamp: daysAgo(REF, 0),
    isTakeaway: true,
  },
  {
    id: "ORD-003",
    customerName: "Andi Wijaya",
    phone: "081122334455",
    type: "Makan di Sini",
    table: "B3",
    items: [
      { name: "Classic Tiramisu", quantity: 1, price: 30000 },
      { name: "Pistachio Baklava", quantity: 2, price: 20000 },
    ],
    totalPrice: 70000,
    status: "Paid",
    timestamp: daysAgo(REF, 0),
    isTakeaway: false,
  },
  {
    id: "ORD-004",
    customerName: "Dewi Lestari",
    phone: "085566778899",
    type: "Makan di Sini",
    table: "A2",
    items: [{ name: "Lemon Meringue Pie", quantity: 1, price: 25000 }],
    totalPrice: 25000,
    status: "Paid",
    timestamp: daysAgo(REF, 0),
    isTakeaway: false,
  },
  {
    id: "ORD-005",
    customerName: "Rian Hidayat",
    phone: "082233445566",
    type: "Pre-Order",
    people: 2,
    items: [
      { name: "Red Velvet Cake", quantity: 2, price: 25000 },
      { name: "Salted Caramel Brownie", quantity: 1, price: 25000 },
    ],
    totalPrice: 75000,
    status: "Pending",
    timestamp: daysAgo(REF, 0),
    isTakeaway: false,
  },
  {
    id: "ORD-006",
    customerName: "Eko Prasetyo",
    phone: "083344556677",
    type: "Makan di Sini",
    table: "C1",
    items: [{ name: "Vanilla Panna Cotta", quantity: 1, price: 35000 }],
    totalPrice: 35000,
    status: "Paid",
    timestamp: daysAgo(REF, 0),
    isTakeaway: false,
  },
  {
    id: "ORD-007",
    customerName: "Linda Wahyuni",
    phone: "084455667788",
    type: "Bawa Pulang",
    table: "A4",
    items: [{ name: "Waffle with Berries", quantity: 1, price: 35000 }],
    totalPrice: 35000,
    status: "Paid",
    timestamp: daysAgo(REF, 0),
    isTakeaway: true,
  },
  // --- Day 1 ---
  {
    id: "ORD-008",
    customerName: "Hendra Kurniawan",
    phone: "085566778811",
    type: "Makan di Sini",
    table: "B2",
    items: [{ name: "Macaron Mix of Five", quantity: 2, price: 45000 }],
    totalPrice: 90000,
    status: "Paid",
    timestamp: daysAgo(REF, 1),
    isTakeaway: false,
  },
  {
    id: "ORD-009",
    customerName: "Nina Marlina",
    phone: "086677889922",
    type: "Reservasi",
    people: 6,
    items: [{ name: "Classic Tiramisu", quantity: 4, price: 30000 }],
    totalPrice: 120000,
    status: "Paid",
    timestamp: daysAgo(REF, 1),
    isTakeaway: false,
  },
  {
    id: "ORD-010",
    customerName: "Yanto",
    phone: "087788990033",
    type: "Makan di Sini",
    table: "A3",
    items: [{ name: "Pistachio Baklava", quantity: 5, price: 20000 }],
    totalPrice: 100000,
    status: "Paid",
    timestamp: daysAgo(REF, 1),
    isTakeaway: false,
  },
  {
    id: "ORD-011",
    customerName: "Ratna Sari",
    phone: "088899001144",
    type: "Bawa Pulang",
    items: [{ name: "Waffle with Berries", quantity: 3, price: 35000 }],
    totalPrice: 105000,
    status: "Paid",
    timestamp: daysAgo(REF, 1),
    isTakeaway: true,
  },
  {
    id: "ORD-012",
    customerName: "Doni Pratama",
    phone: "089900112255",
    type: "Makan di Sini",
    table: "D1",
    items: [
      { name: "Red Velvet Cake", quantity: 2, price: 25000 },
      { name: "Lemon Meringue Pie", quantity: 1, price: 25000 },
    ],
    totalPrice: 75000,
    status: "Paid",
    timestamp: daysAgo(REF, 1),
    isTakeaway: false,
  },
  // --- Day 2 ---
  {
    id: "ORD-013",
    customerName: "Mega Putri",
    phone: "081100223366",
    type: "Makan di Sini",
    table: "A5",
    items: [{ name: "Vanilla Bean Crème Brûlée", quantity: 2, price: 40000 }],
    totalPrice: 80000,
    status: "Paid",
    timestamp: daysAgo(REF, 2),
    isTakeaway: false,
  },
  {
    id: "ORD-014",
    customerName: "Agus Setiawan",
    phone: "082211334477",
    type: "Pre-Order",
    people: 8,
    items: [
      { name: "Macaron Mix of Five", quantity: 5, price: 45000 },
      { name: "Classic Tiramisu", quantity: 3, price: 30000 },
    ],
    totalPrice: 315000,
    status: "Paid",
    timestamp: daysAgo(REF, 2),
    isTakeaway: false,
  },
  {
    id: "ORD-015",
    customerName: "Fitri Handayani",
    phone: "083322445588",
    type: "Bawa Pulang",
    items: [{ name: "Salted Caramel Brownie", quantity: 4, price: 25000 }],
    totalPrice: 100000,
    status: "Paid",
    timestamp: daysAgo(REF, 2),
    isTakeaway: true,
  },
  {
    id: "ORD-016",
    customerName: "Bambang Susilo",
    phone: "084433556699",
    type: "Makan di Sini",
    table: "B4",
    items: [{ name: "Waffle with Berries", quantity: 2, price: 35000 }],
    totalPrice: 70000,
    status: "Paid",
    timestamp: daysAgo(REF, 2),
    isTakeaway: false,
  },
  // --- Day 3 ---
  {
    id: "ORD-017",
    customerName: "Citra Dewi",
    phone: "085544667700",
    type: "Reservasi",
    people: 4,
    items: [
      { name: "Vanilla Panna Cotta", quantity: 3, price: 35000 },
      { name: "Pistachio Baklava", quantity: 4, price: 20000 },
    ],
    totalPrice: 185000,
    status: "Paid",
    timestamp: daysAgo(REF, 3),
    isTakeaway: false,
  },
  {
    id: "ORD-018",
    customerName: "Dimas Aditya",
    phone: "086655778811",
    type: "Makan di Sini",
    table: "C2",
    items: [{ name: "Classic Tiramisu", quantity: 2, price: 30000 }],
    totalPrice: 60000,
    status: "Paid",
    timestamp: daysAgo(REF, 3),
    isTakeaway: false,
  },
  {
    id: "ORD-019",
    customerName: "Erna Susanti",
    phone: "087766889922",
    type: "Bawa Pulang",
    items: [{ name: "Red Velvet Cake", quantity: 3, price: 25000 }],
    totalPrice: 75000,
    status: "Paid",
    timestamp: daysAgo(REF, 3),
    isTakeaway: true,
  },
  {
    id: "ORD-020",
    customerName: "Fajar Nugroho",
    phone: "088877990033",
    type: "Makan di Sini",
    table: "A6",
    items: [
      { name: "Macaron Mix of Five", quantity: 1, price: 45000 },
      { name: "Lemon Meringue Pie", quantity: 2, price: 25000 },
    ],
    totalPrice: 95000,
    status: "Paid",
    timestamp: daysAgo(REF, 3),
    isTakeaway: false,
  },
  // --- Day 4 ---
  {
    id: "ORD-021",
    customerName: "Gita Purnama",
    phone: "089988001144",
    type: "Makan di Sini",
    table: "B5",
    items: [{ name: "Waffle with Berries", quantity: 4, price: 35000 }],
    totalPrice: 140000,
    status: "Paid",
    timestamp: daysAgo(REF, 4),
    isTakeaway: false,
  },
  {
    id: "ORD-022",
    customerName: "Hani Rahayu",
    phone: "081099112255",
    type: "Pre-Order",
    people: 3,
    items: [{ name: "Vanilla Bean Crème Brûlée", quantity: 3, price: 40000 }],
    totalPrice: 120000,
    status: "Paid",
    timestamp: daysAgo(REF, 4),
    isTakeaway: false,
  },
  {
    id: "ORD-023",
    customerName: "Irfan Maulana",
    phone: "082100223366",
    type: "Bawa Pulang",
    items: [
      { name: "Salted Caramel Brownie", quantity: 2, price: 25000 },
      { name: "Pistachio Baklava", quantity: 3, price: 20000 },
    ],
    totalPrice: 110000,
    status: "Paid",
    timestamp: daysAgo(REF, 4),
    isTakeaway: true,
  },
  // --- Day 5 ---
  {
    id: "ORD-024",
    customerName: "Joko Widodo",
    phone: "083211334477",
    type: "Makan di Sini",
    table: "D2",
    items: [
      { name: "Classic Tiramisu", quantity: 3, price: 30000 },
      { name: "Macaron Mix of Five", quantity: 2, price: 45000 },
    ],
    totalPrice: 180000,
    status: "Paid",
    timestamp: daysAgo(REF, 5),
    isTakeaway: false,
  },
  {
    id: "ORD-025",
    customerName: "Kartini Wulandari",
    phone: "084322445588",
    type: "Reservasi",
    people: 10,
    items: [
      { name: "Waffle with Berries", quantity: 6, price: 35000 },
      { name: "Red Velvet Cake", quantity: 4, price: 25000 },
    ],
    totalPrice: 310000,
    status: "Paid",
    timestamp: daysAgo(REF, 5),
    isTakeaway: false,
  },
  {
    id: "ORD-026",
    customerName: "Lukman Hakim",
    phone: "085433556699",
    type: "Makan di Sini",
    table: "A7",
    items: [{ name: "Vanilla Panna Cotta", quantity: 2, price: 35000 }],
    totalPrice: 70000,
    status: "Paid",
    timestamp: daysAgo(REF, 5),
    isTakeaway: false,
  },
  // --- Day 6 ---
  {
    id: "ORD-027",
    customerName: "Maya Sari",
    phone: "086544667700",
    type: "Bawa Pulang",
    items: [{ name: "Lemon Meringue Pie", quantity: 3, price: 25000 }],
    totalPrice: 75000,
    status: "Paid",
    timestamp: daysAgo(REF, 6),
    isTakeaway: true,
  },
  {
    id: "ORD-028",
    customerName: "Nanda Putra",
    phone: "087655778811",
    type: "Makan di Sini",
    table: "C3",
    items: [
      { name: "Macaron Mix of Five", quantity: 4, price: 45000 },
      { name: "Classic Tiramisu", quantity: 2, price: 30000 },
    ],
    totalPrice: 240000,
    status: "Paid",
    timestamp: daysAgo(REF, 6),
    isTakeaway: false,
  },
  // --- Day 8-14 ---
  {
    id: "ORD-029",
    customerName: "Oki Firmansyah",
    phone: "088766889922",
    type: "Makan di Sini",
    table: "B6",
    items: [{ name: "Waffle with Berries", quantity: 3, price: 35000 }],
    totalPrice: 105000,
    status: "Paid",
    timestamp: daysAgo(REF, 8),
    isTakeaway: false,
  },
  {
    id: "ORD-030",
    customerName: "Putri Anggraini",
    phone: "089877990033",
    type: "Reservasi",
    people: 5,
    items: [
      { name: "Vanilla Bean Crème Brûlée", quantity: 4, price: 40000 },
      { name: "Pistachio Baklava", quantity: 5, price: 20000 },
    ],
    totalPrice: 260000,
    status: "Paid",
    timestamp: daysAgo(REF, 9),
    isTakeaway: false,
  },
  {
    id: "ORD-031",
    customerName: "Qori Amalia",
    phone: "081988001144",
    type: "Bawa Pulang",
    items: [{ name: "Red Velvet Cake", quantity: 2, price: 25000 }],
    totalPrice: 50000,
    status: "Paid",
    timestamp: daysAgo(REF, 10),
    isTakeaway: true,
  },
  {
    id: "ORD-032",
    customerName: "Rizky Pratama",
    phone: "082099112255",
    type: "Makan di Sini",
    table: "A8",
    items: [{ name: "Classic Tiramisu", quantity: 5, price: 30000 }],
    totalPrice: 150000,
    status: "Paid",
    timestamp: daysAgo(REF, 11),
    isTakeaway: false,
  },
  {
    id: "ORD-033",
    customerName: "Sari Dewi",
    phone: "083100223366",
    type: "Pre-Order",
    people: 7,
    items: [
      { name: "Macaron Mix of Five", quantity: 6, price: 45000 },
      { name: "Waffle with Berries", quantity: 4, price: 35000 },
    ],
    totalPrice: 410000,
    status: "Paid",
    timestamp: daysAgo(REF, 12),
    isTakeaway: false,
  },
  {
    id: "ORD-034",
    customerName: "Tono Santoso",
    phone: "084211334477",
    type: "Makan di Sini",
    table: "D3",
    items: [{ name: "Salted Caramel Brownie", quantity: 3, price: 25000 }],
    totalPrice: 75000,
    status: "Paid",
    timestamp: daysAgo(REF, 13),
    isTakeaway: false,
  },
  {
    id: "ORD-035",
    customerName: "Umi Kalsum",
    phone: "085322445588",
    type: "Bawa Pulang",
    items: [{ name: "Lemon Meringue Pie", quantity: 4, price: 25000 }],
    totalPrice: 100000,
    status: "Paid",
    timestamp: daysAgo(REF, 14),
    isTakeaway: true,
  },
  // --- Day 15-30 ---
  {
    id: "ORD-036",
    customerName: "Vino Ramadhan",
    phone: "086433556699",
    type: "Makan di Sini",
    table: "B7",
    items: [
      { name: "Vanilla Panna Cotta", quantity: 2, price: 35000 },
      { name: "Classic Tiramisu", quantity: 1, price: 30000 },
    ],
    totalPrice: 100000,
    status: "Paid",
    timestamp: daysAgo(REF, 15),
    isTakeaway: false,
  },
  {
    id: "ORD-037",
    customerName: "Wati Suryani",
    phone: "087544667700",
    type: "Reservasi",
    people: 8,
    items: [
      { name: "Waffle with Berries", quantity: 5, price: 35000 },
      { name: "Macaron Mix of Five", quantity: 3, price: 45000 },
    ],
    totalPrice: 310000,
    status: "Paid",
    timestamp: daysAgo(REF, 17),
    isTakeaway: false,
  },
  {
    id: "ORD-038",
    customerName: "Xander Putra",
    phone: "088655778811",
    type: "Makan di Sini",
    table: "C4",
    items: [{ name: "Red Velvet Cake", quantity: 4, price: 25000 }],
    totalPrice: 100000,
    status: "Paid",
    timestamp: daysAgo(REF, 19),
    isTakeaway: false,
  },
  {
    id: "ORD-039",
    customerName: "Yuli Astuti",
    phone: "089766889922",
    type: "Bawa Pulang",
    items: [{ name: "Pistachio Baklava", quantity: 6, price: 20000 }],
    totalPrice: 120000,
    status: "Paid",
    timestamp: daysAgo(REF, 21),
    isTakeaway: true,
  },
  {
    id: "ORD-040",
    customerName: "Zaki Firmansyah",
    phone: "081877990033",
    type: "Makan di Sini",
    table: "A9",
    items: [
      { name: "Vanilla Bean Crème Brûlée", quantity: 3, price: 40000 },
      { name: "Salted Caramel Brownie", quantity: 2, price: 25000 },
    ],
    totalPrice: 170000,
    status: "Paid",
    timestamp: daysAgo(REF, 23),
    isTakeaway: false,
  },
  {
    id: "ORD-041",
    customerName: "Ayu Lestari",
    phone: "082988001144",
    type: "Pre-Order",
    people: 5,
    items: [{ name: "Classic Tiramisu", quantity: 6, price: 30000 }],
    totalPrice: 180000,
    status: "Paid",
    timestamp: daysAgo(REF, 25),
    isTakeaway: false,
  },
  {
    id: "ORD-042",
    customerName: "Bagas Nugroho",
    phone: "083099112255",
    type: "Makan di Sini",
    table: "D4",
    items: [
      { name: "Waffle with Berries", quantity: 4, price: 35000 },
      { name: "Lemon Meringue Pie", quantity: 3, price: 25000 },
    ],
    totalPrice: 215000,
    status: "Paid",
    timestamp: daysAgo(REF, 27),
    isTakeaway: false,
  },
  {
    id: "ORD-043",
    customerName: "Candra Wijaya",
    phone: "084100223366",
    type: "Reservasi",
    people: 12,
    items: [
      { name: "Macaron Mix of Five", quantity: 8, price: 45000 },
      { name: "Red Velvet Cake", quantity: 6, price: 25000 },
    ],
    totalPrice: 510000,
    status: "Paid",
    timestamp: daysAgo(REF, 29),
    isTakeaway: false,
  },
];

export const MENU_MOCK = [
  {
    name: "Waffle with Berries",
    category: "Waffle",
    price: 35000,
    stock: 15,
    status: "Available",
  },
  {
    name: "Vanilla Bean Crème Brûlée",
    category: "Crème Brûlée",
    price: 40000,
    stock: 10,
    status: "Available",
  },
  {
    name: "Macaron Mix of Five",
    category: "Macaron",
    price: 45000,
    stock: 0,
    status: "Sold Out",
  },
  {
    name: "Classic Tiramisu",
    category: "Tiramisu",
    price: 30000,
    stock: 20,
    status: "Available",
  },
  {
    name: "Pistachio Baklava",
    category: "Baklava",
    price: 20000,
    stock: 12,
    status: "Available",
  },
  {
    name: "Lemon Meringue Pie",
    category: "Pie",
    price: 25000,
    stock: 8,
    status: "Available",
  },
  {
    name: "Red Velvet Cake",
    category: "Cake",
    price: 25000,
    stock: 10,
    status: "Available",
  },
  {
    name: "Salted Caramel Brownie",
    category: "Brownie",
    price: 25000,
    stock: 5,
    status: "Available",
  },
  {
    name: "Vanilla Panna Cotta",
    category: "Panna Cotta",
    price: 35000,
    stock: 0,
    status: "Sold Out",
  },
];

export const REVENUE_MOCK = [
  { day: "Senin", income: 1200000 },
  { day: "Selasa", income: 1500000 },
  { day: "Rabu", income: 1100000 },
  { day: "Kamis", income: 1800000 },
  { day: "Jumat", income: 2200000 },
  { day: "Sabtu", income: 3500000 },
  { day: "Minggu", income: 2800000 },
];
